name: Assistente CI-CD Workflow.

on:
  push:
    branches:
      - backend-mvp
  pull_request:
    branches:
      - backend-mvp

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Create env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Building Docker Image for Backend
        run: docker build -t aceleraprojetosfjs/assistentevirtual-backend:latest ./backend

      - name: Pushing Docker Image for Backend
        run: docker push aceleraprojetosfjs/assistentevirtual-backend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Re-create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker Image for Backend
        run: docker pull aceleraprojetosfjs/assistentevirtual-backend:latest

      - name: Stop and Remove Old Backend Container
        run: docker rm -f backend-container 

      - name: Deploy Docker Container for Backend
        run: docker run -d --name backend-container --env-file .env -p 3000:80 aceleraprojetosfjs/assistentevirtual-backend:latest
