name: Node-Backend CI-CD
on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm install

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t acelerafjsprojetos/backendassistente .
          docker push acelerafjsprojetos/backendassistente

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull the latest Docker image
        run: docker pull acelerafjsprojetos/backendassistente

      - name: Stop the current container
        run: docker stop nodejsContainer || true

      - name: Remove the stopped container
        run: docker rm nodejsContainer || true

      - name: Run the new container
        run: docker run -d --restart=always --name nodejsContainer -p 8000:8000 acelerafjsprojetos/backendassistente:latest
